### ISSUE TITLE
Characters following a hash `#` within a regex treated as a comment

### ISSUE THREAD

**Issue by jorgebucaran** [JohnNilsson/awk-sublime#12]
If a regex contains a hash `#` the rest of the characters are incorrectly treated as a comment.

### Desired Behavior 

> GitHub Code Block

```awk
/^#/ { print (n ? "\n" : "")$0 }
```

### Actual Behavior 
> Visual Studio Code

![untitled](https://user-images.githubusercontent.com/56996/45529146-939efd00-b81e-11e8-9a39-f0d9ee5788da.png)

**Comment by KyrosKrane** [comment]
The core problem appears to be that the parser isn't treating regular expression literals as literals. In the example above, the slashes in `/^#/` should be treated as delimiters, similar to quotes around a string literal "like this."

A similar problem can be observed when putting quotes inside a regular expression literal. Consider the case where the code might want to replace quote marks inside a variable with something else, such as blanks (removing the quotes).

```awk
MyVar = "The \"quick brown fox\" jumped over the lazy dogs."
gsub(/"/, "", MyVar)
       ^--> display error here due to parser not understanding the RE literal
```

In this case, the parser treats the second slash (closing the RE literal) onwards as part of a string, started by the quote inside the RE literal.

**Comment by JohnNilsson** [comment]
Might have already fixed this at some other time. Only issue I could see now was that the enclosing / wasn't both scoped as `string.regexp`. Just pushed a fix for that at least.
<img width="489" alt="Screenshot 2020-11-29 at 01 13 11" src="https://user-images.githubusercontent.com/97594/100528741-467d8a80-31e0-11eb-8d40-66d3f49aaeee.png">
