### ISSUE TITLE
Comment support?

### ISSUE THREAD

**Issue by nabijaczleweli** [JohnNilsson/awk-sublime#9]
SS illustrating issue:
![SS](https://cloud.githubusercontent.com/assets/6709544/18732434/781e25e6-8063-11e6-951d-f25c02dc53a9.png)

**Comment by JohnNilsson** [comment]
I'm sorry. Illustrating what issue?

**Comment by nabijaczleweli** [comment]
See top of file: comments are not highlighted

**Comment by JohnNilsson** [comment]
![image](https://cloud.githubusercontent.com/assets/97594/18888656/8d3430e8-84f9-11e6-9d3a-eab5ff4f5d18.png)

Works perfectly fine for me. (Build 3126, macOS)

Sure it's not your color theme? It needs to have a color for scope "punctuation.definition.comment.awk"

**Comment by nabijaczleweli** [comment]
I'm using Nexus, comments elsewhere work. How could I verify it has that scope's colour?

**Comment by JohnNilsson** [comment]
Just did, it should work. Shouldn't really work for me though ;)

Ok fix, coming up

**Comment by nabijaczleweli** [comment]
Dope shit :+1:
